### ISSUE TITLE
sudo command not found in biocontainers/biocontainers

### ISSUE THREAD

**Issue by AliciaMstt** [BioContainers/containers#139]
I noticed I could not install things inside the container running as biodocker because sudo was not isntalled ("sudo command not found"). I solved this by entering the container as root and:

```
apt-get update
apt-get install sudo
echo "biodocker ALL=(ALL:ALL) NOPASSWD:ALL" | (EDITOR="tee -a" visudo)
```
Is there any reason why you are not allowing user biodocker to use sudo or is this something you should change in the dockerfile?

Use case: I wanted to install FastXTools and other small tools inside a biocontainers container because it is faster (already got some of the common tools like curl and  zlib1g-dev) than doing it using ubuntu as a base.

**Comment by ypriverol** [comment]
First of all thanks for using biocontainers and contacting us. If you are willing to contribute, please let us know and we can add you to the list of contributors in the biocontainers github organization. 

We have been discussing before multiple reasons why everything should be installed as biocontainers and not root (is reflected in our best practices): 

 - Is the best practices for Linux in general.

 - The reason for install locally instead of globally (all packages) whenever possible is just for 
    good practices. You will (almost) always know when all executable/config files are.
 
 - Biocontainers are "ready to use" software components, then each container should provide the desired software.  If you want to combine software, we recommended to use workflows, like combinations of multiple containers. 

What do you think @prvst @bgruening @sauloal .

As you said, it would be great to have a protocol about what to do in these cases. If @BioContainers/contributors like the idea we can add a short section to **faqs** in the documentation http://biocontainers.pro/docs/101/intro/ to help users with this. And we can use this thread to discuss possible stable solutions.

**Comment by prvst** [comment]
@AliciaMstt There is a general consensus to avoid giving sudo access to users in containers because depending on the environment you are executing the image (e.g clusters), this becomes a security issue. Apparently, there are some ways of using this privilege to manipulate some data from outside the container.

**Comment by AliciaMstt** [comment]
Hi, I see now, it makes sense for security issues in that context. Thanks for the feedback. 

If fine with you @ypriverol et al I would like becoming a contributor. To start with I would like to make the dockerfiles for basic pre-processing software, like FastXtools, Trimmomatic and FastQC. I quickly checked your documentation and best practices regarding dockerfiles and for these programs it should be easy to write it. Besides I could ask my students of this semester to test it prior to commiting it.

Question: my understanding is that Biocontainers policy is one container per softaware, but in the case of the tools mentioned above they are light and work well together, so it may make sense to have them in a single container (something like biocontainers/pre-processingtools)? Only an idea.

**Comment by prvst** [comment]
@AliciaMstt , it's always a pleasure to have more people participating, I will send you an invitation.

About the containers, the main idea is to have atomized processing units, or in other words, simple containers with one software inside. Nevertheless, this is not necessarily am obligation, we have some examples where more than one software is available per container, but I strongly suggest you to make them separate containers (think about workflow systems and pipelines that need to load just one specific software). 

Also, it may become complicated to annotate the container and the metadata if the containers have more than one "main" software.

Please, feel free t write if you still have questions, I will close the issue and then, if necessary, we can set the details in Gitter.
