### ISSUE TITLE
Updating the base image

### ISSUE THREAD

**Issue by prvst** [BioContainers/containers#144]
Hi everyone @BioContainers/contributors;

I want to propose the update of our base image to Ubuntu 16.10. Besides having the latest version, this would also allows us to have the OpenMS package installed via apt get.

Discuss =)

**Comment by bgruening** [comment]
@prvst I think we should only use LTS versions if possible.
Regarding OpenMS, please see here: https://quay.io/repository/biocontainers/openms?tab=tags

**Comment by hroest** [comment]
I agree, LTS should be preferred. From the OpenMS side, I would actually prefer to install OpenMS from github as we will have more up-to-date versions of OpenMS available. Currently these are available https://launchpad.net/ubuntu/+source/openms

- OpenMS 1.11 is available for 14.04 and 15.04
- OpenMS 2.0 is available for 16.10 and 17.04

there was an unfortunate bug in the 16.04 package of Wildmagic that prevents a successful build (linking issue). Also, OpenMS 2.0.0 was released in April 2015 so its not so fresh and we had 2 releases since then (2.0.1 and 2.1.0).
