### ISSUE TITLE
pulling containers from quay.io with docker requires tag 

### ISSUE THREAD

**Issue by brooksph** [BioContainers/containers#169]
I was having trouble pulling some of your containers using the commands you provided. It seems as though docker looking for a "latest" tag and atleast some of your containers lack this tag, thus I had to add :<tag> after your pull command (e.g. docker pull quay.io/biocontainers/trimmomatic:0.36--4).

**Comment by ypriverol** [comment]
We have decided to do not use latest in our containers because of reproducibility issues (what is latest today is probably not the same version in a year time). Soon we will provide a command line tool that enables you to infer what is the latest version. 

Regards and Thanks for using BioContainers.
