### ISSUE TITLE
Questions about biocontainers and quay.io

### ISSUE THREAD

**Issue by srp33** [BioContainers/containers#354]
Thanks for all the great work you've put into BioContainers. I wasn't very familiar with it until recently. I'm wondering if you could answer a few questions.

* On the biocontainers registry, I see many versions of samtools, including several of the latest (1.10). But when I look here, I don't see these same versions. Is there another place where I should look to see the Dockerfile for these versions?
* On bioconda, I see versions 1.9 and 1.10 but not all the other versions.
* Most of the containers appear not to have an entry point (by design, I think). But is there a way to discover what command should be executed for a given container when running it? For example, I can run docker run --rm quay.io/biocontainers/samtools:1.10--h9402c20_2 samtools and that works. But I'm not sure what command to run for many others.

Sorry if these are dumb questions. I can ask them on a different forum if that is better. But thanks for your time!

**Comment by osallou** [comment]
Hi,
Biocontainers have 2 'input sources' for containers:
* bioconda: each package automatically creates a container and is pushed to quay.io (so container name has quay.io prefix). There is no dockerfile because bioconda use a special build system to create them.
* biocontainers github repo  where people contribute with dockerfiles. Once merged, containers are built from dockerfile via our ci system. Containers are hosted on dockerhub abd prefuxed biocontainers.

You may find same tool and same version on both,  because we import debian packages too, and some people want a container with a different base image to access bash, vi etc... Bioconda containers are Alpine based and only have tool installed. Biocontainers docker based ones are based on an ubuntu system.


At last, regarding entrypoint, there are none because it creates issues with some tools calling docker and willing to call tools in containers. Furthermore some containers have different binaries, so can't set 1 entrypoint.
So all containers must be called with, as arg, the binary to execute, which *should* be in container PATH

I hope it answer your questions.

**Comment by srp33** [comment]
Thanks so much.
