### ISSUE TITLE
Container request: ARPEGGIO

### ISSUE THREAD

**Issue by supermaxiste** [BioContainers/containers#406]
Dear BioContainers team,

To further ensure reproducibility, I would like to request a BioContainer for my tool ARPEGGIO, which can be found at https://github.com/supermaxiste/ARPEGGIO. The repository already includes a Dockerfile.

Thank you for supporting this great BioContainers project and looking forward to your answer.

Stefan

**Comment by osallou** [comment]
Hi,
not sure to understand your tool. I had a look with updates to dockerfile, but you only install dependencies, nothing related to your tool itself. Is goal only to use image with "snakemake --use-conda --use-singularity" case ?

Furthermore, it creates a huge container with multiple tools. As you use snakemake for a workflow, why not calling each tool with its own container rather than calling the same container again and again with everything inside?

**Comment by supermaxiste** [comment]
Hi,

thank you for the reply. It's indeed better to containerize each tool or each environment rather than everything, so I'll follow that suggestion.
