### ISSUE TITLE
Best practice for installing software from scratch

### ISSUE THREAD

**Issue by rjpbonnal** [BioContainers/containers#73]
Looking at the Dockerfile, the biodocker user installs everything locally.  I was used to install everything as root. Today I noticed some problem with ADD and premises when I am unpacking/compiling/installing software as non-root in the user local directory.

A container is by itself, if it is dirty for a ./configure; make;make install; who cares ?

We can still use the biodocker user as generic user. Actually for my specific use cases I am mapping the uid e gid to the real users

**Comment by sauloal** [comment]
sorry. I can't understand your question(s).

Which issues did you find with ADD?

The whole point of not running as root is that this is the best practices for linux in general.

The reason to installing locally instead of globally whenever possible is just for convenience. you will (almost) always know when all executable/config files are.

We care if a container is dirty with configure/make because it makes it slower and bigger (in size and layers).
