### ISSUE TITLE
OpenMS container has a dockerhub placeholder under biocontainers, but no container

### ISSUE THREAD

**Issue by pcm32** [BioContainers/containers#82]
I came accross today a container on dockerhub (this one is not present in the registry UI) which doesn't seem to have any tags available nor being pushed:

https://hub.docker.com/r/biocontainers/openms/

On this one builds failed apparently. But I guess we probably want to clean up those from docker hub to avoid users being discouraged by thinking that the containers are not working/not available. This was also under biodckr user on dockerhub as well I think. You probably want to get rid of that user, or of its containers.

**Comment by prvst** [comment]
Hy @pcm32 , This container is a work-in-progress, we are having issues with it because of the way how Docker Hub works, they are limiting resources for building new containers and that is why those are failing. I'm still thinking on how to circumvent that, if there is no practical way, then we can remove it.
